name: WebdriverIO Tests

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome-firefox:latest
        ports:
          - 4444:4444

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      # Run tests and generate Allure results
      - name: Run All Tests
        run: |
          npm run test:chrome
          npm run test:firefox
        continue-on-error: true 

      # Generate Allure Report
      - name: Generate Allure Report
        if: always()
        run: |
          allure generate allure-results --clean -o allure-report
          
      - name: Upload Test Results as Artifacts  
        uses: actions/upload-artifact@v4
        with:
          name: RunReports
          path: allure-results

      - name: Upload Report for GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: allure-results 

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5
        with:
          enablement: true

      - name: Deploy Report to GitHub Pages
        uses: actions/deploy-pages@v4